/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'published' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'imageUrl' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'review' : IDL.Text,
  'clientName' : IDL.Text,
  'order' : IDL.Nat,
  'clientImage' : IDL.Text,
  'rating' : IDL.Nat,
});
export const SiteSettings = IDL.Record({
  'aboutImage' : IDL.Text,
  'heroHeading' : IDL.Text,
  'yearsExp' : IDL.Nat,
  'twitter' : IDL.Text,
  'tagline' : IDL.Text,
  'instagram' : IDL.Text,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'facebook' : IDL.Text,
  'awards' : IDL.Nat,
  'address' : IDL.Text,
  'aboutText' : IDL.Text,
  'youtube' : IDL.Text,
  'phone' : IDL.Text,
  'happyClients' : IDL.Nat,
  'heroSubheading' : IDL.Text,
  'projectsCompleted' : IDL.Nat,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'budget' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([UserId], [], []),
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [BlogPost],
      [],
    ),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [GalleryImage],
      [],
    ),
  'addPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [PortfolioItem],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Service],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [Testimonial],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getPortfolioItem' : IDL.Func([IDL.Nat], [IDL.Opt(PortfolioItem)], ['query']),
  'getSettings' : IDL.Func([], [SiteSettings], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'listPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'listPortfolioItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'listPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'removeAdmin' : IDL.Func([UserId], [], []),
  'saveContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactMessage],
      [],
    ),
  'setFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'toggleFeaturedPortfolioItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateBlogPost' : IDL.Func([BlogPost], [IDL.Bool], []),
  'updateGalleryImage' : IDL.Func([GalleryImage], [IDL.Bool], []),
  'updatePortfolioItem' : IDL.Func([PortfolioItem], [IDL.Bool], []),
  'updateService' : IDL.Func([Service], [IDL.Bool], []),
  'updateSettings' : IDL.Func([SiteSettings], [], []),
  'updateTestimonial' : IDL.Func([Testimonial], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'published' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'imageUrl' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'review' : IDL.Text,
    'clientName' : IDL.Text,
    'order' : IDL.Nat,
    'clientImage' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({
    'aboutImage' : IDL.Text,
    'heroHeading' : IDL.Text,
    'yearsExp' : IDL.Nat,
    'twitter' : IDL.Text,
    'tagline' : IDL.Text,
    'instagram' : IDL.Text,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'facebook' : IDL.Text,
    'awards' : IDL.Nat,
    'address' : IDL.Text,
    'aboutText' : IDL.Text,
    'youtube' : IDL.Text,
    'phone' : IDL.Text,
    'happyClients' : IDL.Nat,
    'heroSubheading' : IDL.Text,
    'projectsCompleted' : IDL.Nat,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'budget' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([UserId], [], []),
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [BlogPost],
        [],
      ),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [GalleryImage],
        [],
      ),
    'addPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [PortfolioItem],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Service],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [Testimonial],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getPortfolioItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PortfolioItem)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [SiteSettings], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'listPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'listPortfolioItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'listPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'removeAdmin' : IDL.Func([UserId], [], []),
    'saveContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactMessage],
        [],
      ),
    'setFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'toggleFeaturedPortfolioItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateBlogPost' : IDL.Func([BlogPost], [IDL.Bool], []),
    'updateGalleryImage' : IDL.Func([GalleryImage], [IDL.Bool], []),
    'updatePortfolioItem' : IDL.Func([PortfolioItem], [IDL.Bool], []),
    'updateService' : IDL.Func([Service], [IDL.Bool], []),
    'updateSettings' : IDL.Func([SiteSettings], [], []),
    'updateTestimonial' : IDL.Func([Testimonial], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };