/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : string,
  'published' : boolean,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'service' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'budget' : string,
}
export interface GalleryImage {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'imageUrl' : string,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'order' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'icon' : string,
  'description' : string,
}
export interface SiteSettings {
  'aboutImage' : string,
  'heroHeading' : string,
  'yearsExp' : bigint,
  'twitter' : string,
  'tagline' : string,
  'instagram' : string,
  'businessName' : string,
  'email' : string,
  'facebook' : string,
  'awards' : bigint,
  'address' : string,
  'aboutText' : string,
  'youtube' : string,
  'phone' : string,
  'happyClients' : bigint,
  'heroSubheading' : string,
  'projectsCompleted' : bigint,
}
export interface Testimonial {
  'id' : bigint,
  'review' : string,
  'clientName' : string,
  'order' : bigint,
  'clientImage' : string,
  'rating' : bigint,
}
export type UserId = Principal;
export interface _SERVICE {
  'addAdmin' : ActorMethod<[UserId], undefined>,
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, string, boolean],
    BlogPost
  >,
  'addGalleryImage' : ActorMethod<[string, string, bigint], GalleryImage>,
  'addPortfolioItem' : ActorMethod<
    [string, string, string, string, boolean, bigint],
    PortfolioItem
  >,
  'addService' : ActorMethod<[string, string, string, bigint], Service>,
  'addTestimonial' : ActorMethod<
    [string, string, string, bigint, bigint],
    Testimonial
  >,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'deleteGalleryImage' : ActorMethod<[bigint], boolean>,
  'deletePortfolioItem' : ActorMethod<[bigint], boolean>,
  'deleteService' : ActorMethod<[bigint], boolean>,
  'deleteTestimonial' : ActorMethod<[bigint], boolean>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getPortfolioItem' : ActorMethod<[bigint], [] | [PortfolioItem]>,
  'getSettings' : ActorMethod<[], SiteSettings>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listAdmins' : ActorMethod<[], Array<UserId>>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'listPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'listPortfolioItemsByCategory' : ActorMethod<[string], Array<PortfolioItem>>,
  'listPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'listTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'removeAdmin' : ActorMethod<[UserId], undefined>,
  'saveContactMessage' : ActorMethod<
    [string, string, string, string, string],
    ContactMessage
  >,
  'setFirstAdmin' : ActorMethod<[], boolean>,
  'toggleFeaturedPortfolioItem' : ActorMethod<[bigint], boolean>,
  'updateBlogPost' : ActorMethod<[BlogPost], boolean>,
  'updateGalleryImage' : ActorMethod<[GalleryImage], boolean>,
  'updatePortfolioItem' : ActorMethod<[PortfolioItem], boolean>,
  'updateService' : ActorMethod<[Service], boolean>,
  'updateSettings' : ActorMethod<[SiteSettings], undefined>,
  'updateTestimonial' : ActorMethod<[Testimonial], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];